/**
 * Trailhead template renderer. Produces static HTML files from built site
 * content. Designed for both live serving (via the trailhead-site route) and
 * static export (zip bundle in stage 6).
 *
 * Every page is a self-contained HTML document with inlined CSS: no external
 * dependencies, no JavaScript framework, no build step. This is what makes
 * the export promise real from day one.
 */

import type { BuiltSite } from "./spark-trailhead";

export interface RenderedPage {
  slug: string;
  filename: string;
  title: string;
  html: string;
}

/**
 * How internal navigation links are written:
 * - "export": static files on disk (`/index.html`, `/about.html`). This is the
 *   self-contained bundle that backs the export zip and works without the app.
 * - "live": app-routable paths (`/`, `/about`) served at the public subdomain.
 * - "preview": token-scoped links through the app, so the customer can view the
 *   preview before public DNS exists.
 */
export type LinkStyle = "export" | "live" | "preview";

function navHref(
  slug: string,
  linkStyle: LinkStyle,
  token?: string,
): string {
  const isHome = slug === "home";
  switch (linkStyle) {
    case "live":
      return isHome ? "/" : `/${slug}`;
    case "preview":
      return isHome
        ? `/api/trailhead/preview/${token}`
        : `/api/trailhead/preview/${token}?page=${encodeURIComponent(slug)}`;
    case "export":
    default:
      return isHome ? "/index.html" : `/${slug}.html`;
  }
}

/**
 * Rewrite internal page links in built page HTML to match the serving context.
 *
 * Spark writes in-content links (CTA buttons, "learn more" links) as bare page
 * slugs, e.g. `href="about"`, because it is given the navigation slug list and
 * told to link to those pages. Only the site chrome (nav) is generated by this
 * renderer, so those body links passed through verbatim and broke everywhere
 * except the home page: the export bundle 404s (the file is `about.html`), and
 * preview links drop the token and page param, dumping the visitor out of the
 * preview. This maps any link whose target resolves to a known page slug onto
 * the same href the nav uses for the current link style, so body links and nav
 * links stay in lockstep. Links to unknown targets, external URLs, mailto/tel,
 * and pure fragments are left untouched.
 */
function rewriteInternalLinks(
  html: string,
  slugToHref: Map<string, string>,
  homeHref: string,
): string {
  return html.replace(
    /(href\s*=\s*)(["'])([^"']*)\2/gi,
    (whole, prefix: string, quote: string, value: string) => {
      const raw = value.trim();
      // Leave external links, schemes (mailto:, tel:, http(s):), protocol-
      // relative URLs, and pure fragments/queries alone.
      if (
        raw === "" ||
        raw.startsWith("#") ||
        raw.startsWith("?") ||
        raw.startsWith("//") ||
        /^[a-z][a-z0-9+.-]*:/i.test(raw)
      ) {
        return whole;
      }
      // Preserve a trailing #fragment on an internal link.
      const hashIndex = raw.indexOf("#");
      const fragment = hashIndex === -1 ? "" : raw.slice(hashIndex);
      let path = hashIndex === -1 ? raw : raw.slice(0, hashIndex);
      // Normalize: drop ./ and leading/trailing slashes, an .html extension,
      // and any query string, then match case-insensitively against slugs.
      path = path.replace(/^\.?\//, "").replace(/\/+$/, "").split("?")[0];
      const key = path.replace(/\.html$/i, "").toLowerCase();
      const target =
        key === "" || key === "index" || key === "home"
          ? homeHref
          : slugToHref.get(key);
      if (target === undefined) return whole;
      return `${prefix}${quote}${escapeAttr(target + fragment)}${quote}`;
    },
  );
}

/**
 * Render a full static HTML page from a built page and the site config.
 * The output is a complete, standalone HTML document.
 */
export function renderPage(
  site: BuiltSite,
  pageIndex: number,
  subdomain: string,
  linkStyle: LinkStyle = "export",
  token?: string,
): RenderedPage | null {
  const page = site.pages[pageIndex];
  if (!page) return null;

  const nav = site.config.navigation ?? [];
  const siteName = site.config.siteName ?? subdomain;
  const footerCredit = site.config.footerCredit !== false;

  // Map every known page slug to its href for the current link style, so body
  // links Spark wrote as bare slugs point where the nav points. Built from the
  // page list (the source of truth for what exists), keyed lowercase.
  const slugToHref = new Map<string, string>();
  for (const p of site.pages) {
    slugToHref.set(p.slug.toLowerCase(), navHref(p.slug, linkStyle, token));
  }
  const homePage = site.pages.find((p) => p.slug === "home") ?? site.pages[0];
  const homeHref = navHref(homePage?.slug ?? "home", linkStyle, token);
  const pageBody = rewriteInternalLinks(page.html ?? "", slugToHref, homeHref);

  const navHtml = nav
    .map((item) => {
      const href = navHref(item.slug, linkStyle, token);
      const active = item.slug === page.slug ? ' class="active"' : "";
      return `<a href="${escapeAttr(href)}"${active}>${escapeHtml(item.label)}</a>`;
    })
    .join("\n        ");

  const footerHtml = footerCredit
    ? `\n      <p class="db-credit"><a href="https://doubleblaze.solutions">Built by Double Blaze</a></p>`
    : "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(page.title)} | ${escapeHtml(siteName)}</title>
  <style>
/* Navigation */
nav.site-nav {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 1rem;
  padding: 1rem 2rem;
  background: inherit;
}
nav.site-nav .site-name {
  font-weight: 700;
  font-size: 1.25rem;
  margin-right: auto;
}
nav.site-nav a {
  text-decoration: none;
  color: inherit;
}
nav.site-nav a.active {
  font-weight: 600;
}
nav.site-nav a:hover {
  opacity: 0.8;
}

/* Footer */
footer.site-footer {
  padding: 2rem;
  text-align: center;
  font-size: 0.875rem;
  opacity: 0.7;
}
footer.site-footer .db-credit a {
  color: inherit;
  text-decoration: underline;
}

/* Base reset */
*, *::before, *::after { box-sizing: border-box; }
body { margin: 0; font-family: system-ui, -apple-system, sans-serif; line-height: 1.6; }
img { max-width: 100%; height: auto; }
  </style>
</head>
<body>
  <nav class="site-nav" role="navigation" aria-label="Main navigation">
    <span class="site-name">${escapeHtml(siteName)}</span>
    ${navHtml}
  </nav>

  <main>
    ${pageBody}
  </main>

  <footer class="site-footer">
    <p>${escapeHtml(siteName)}</p>${footerHtml}
  </footer>
</body>
</html>`;

  return {
    slug: page.slug,
    filename: page.slug === "home" ? "index.html" : `${page.slug}.html`,
    title: page.title,
    html,
  };
}

/**
 * Render all pages of a site. Returns an array of rendered pages suitable
 * for both live serving and zip export.
 */
export function renderAllPages(site: BuiltSite, subdomain: string): RenderedPage[] {
  const pages: RenderedPage[] = [];
  for (let i = 0; i < site.pages.length; i++) {
    const rendered = renderPage(site, i, subdomain, "export");
    if (rendered) pages.push(rendered);
  }
  return pages;
}

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}
