import type { Metadata } from "next";
import Link from "next/link";
import { PageHero } from "@/components/PageHero";
import gallery from "@/data/prototype-gallery.json";

/**
 * The Trail Crew gallery: every student team's prototype in one place.
 *
 * The manifest is generated by `npm run prototypes` and committed, and the
 * prototypes themselves are static files under `public/prototypes`. Nothing
 * here reads a database or runs at request time, which is deliberate: a page
 * showing minors' class work should have no moving parts and no way to leak
 * anything that was not committed on purpose.
 *
 * Team names and product names only. No student names, ever.
 */

interface GalleryEntry {
  slug: string;
  productName: string;
  teamName?: string;
  purpose: string;
  features: string[];
  href: string;
  stats: { features: number; stories: number; scenarios: number; screens: number };
  gaps: number;
  buildHref?: string;
  designHref?: string;
  testPlanHref?: string;
  gapHref?: string;
  stage?: string;
  next?: string;
}

/**
 * The chain, and what to call each step on screen.
 *
 * Kept in the same order as the generator's, because the board reads left to
 * right as a progress bar and a team's position in it is the whole point.
 */
const STAGES = ["plan", "stories", "cards", "architecture", "build"] as const;

const STAGE_LABEL: Record<string, string> = {
  plan: "Product plan",
  stories: "User stories",
  cards: "Build cards",
  architecture: "Architecture",
  build: "Figma and Anvil",
};

const teams = gallery as GalleryEntry[];

/**
 * Teams whose app was built as a live site rather than in Anvil.
 *
 * A literal map rather than something generated, because there is one of them.
 * Classic Cars is three people with no developer, so they got the site built
 * and the admin console behind it, which is the part of the web nobody shows a
 * thirteen year old. If a second team ends up here, this is still the right
 * shape; if a fifth does, it belongs in the team's folder instead.
 */
const LIVE_SITES: Record<string, string> = {
  "period-2-classic-cars": "/trail-crew/classic-cars",
};

export const metadata: Metadata = {
  title: "Trail Crew: student prototypes",
  description:
    "Product plans and user stories written by student teams, turned into clickable prototypes. Every screen came from something a team wrote.",
  robots: { index: false, follow: false },
};

/**
 * Every team's step and their one next thing, in a table.
 *
 * This exists because the gap guides were unfindable. Each one was the fifth of
 * five identical outlined buttons on a card, below the fold, and a link nobody
 * clicks is a page nobody reads. Sorted by how far along a team is, so whoever
 * needs help most is at the top.
 */
function ClassBoard({ teams }: { teams: GalleryEntry[] }) {
  const ordered = [...teams]
    .filter((t) => t.gapHref)
    .sort((a, b) => {
      const s =
        STAGES.indexOf((a.stage ?? "plan") as (typeof STAGES)[number]) -
        STAGES.indexOf((b.stage ?? "plan") as (typeof STAGES)[number]);
      return s !== 0 ? s : a.productName.localeCompare(b.productName);
    });

  if (ordered.length === 0) return null;

  return (
    <section className="border-b border-ink/10 bg-white">
      <div className="container-page py-10">
        <p className="eyebrow">Where everyone is</p>
        <h2 className="mt-2 font-display text-2xl font-bold text-ink">
          Every team, and the one thing they do next
        </h2>
        <p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink/70">
          Worked out from each team&rsquo;s own documents, not from anybody&rsquo;s opinion of
          them. Teams with the furthest to go are at the top. Open a row for the
          whole list and a helper that has that team&rsquo;s work in front of it.
        </p>

        <div className="mt-6 overflow-x-auto">
          <table className="w-full min-w-[46rem] border-collapse text-left text-sm">
            <thead>
              <tr className="border-b border-ink/15 text-xs uppercase tracking-wide text-hokie-gray">
                <th scope="col" className="py-2 pr-4 font-semibold">
                  Team
                </th>
                <th scope="col" className="whitespace-nowrap py-2 pr-4 font-semibold">
                  On this step
                </th>
                <th scope="col" className="py-2 pr-4 font-semibold">
                  Next thing
                </th>
                <th scope="col" className="py-2 font-semibold">
                  <span className="sr-only">Gap guide</span>
                </th>
              </tr>
            </thead>
            <tbody>
              {ordered.map((team) => (
                <tr key={team.slug} className="border-b border-ink/10 align-top">
                  <td className="py-3 pr-4 font-semibold text-blaze-maroon">
                    {team.productName}
                    {team.teamName &&
                      team.teamName.trim().toLowerCase() !==
                        team.productName.trim().toLowerCase() && (
                        <span className="block text-xs font-normal text-hokie-gray">
                          {team.teamName}
                        </span>
                      )}
                  </td>
                  <td className="whitespace-nowrap py-3 pr-4">
                    <span className="rounded-full bg-blaze-maroon/5 px-2.5 py-1 text-xs text-blaze-maroon">
                      {STAGE_LABEL[team.stage ?? "plan"] ?? team.stage}
                    </span>
                  </td>
                  <td className="py-3 pr-4 text-ink/75">
                    {team.next ?? "Nothing this page can see. Go and build."}
                  </td>
                  <td className="py-3 whitespace-nowrap">
                    <a
                      href={team.gapHref}
                      className="font-medium text-blaze-maroon underline underline-offset-2 hover:text-trail-orange"
                      target="_blank"
                      rel="noopener"
                    >
                      What next
                    </a>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

export default function TrailCrewPage() {
  return (
    <>
      <PageHero
        eyebrow="Trail Crew"
        title="They wrote it down. Here is what it looks like."
        intro="Every prototype below was generated from a student team's product plan and user stories. No design work, no code, and nothing invented by us. The words are theirs, the screens follow."
      />

      <ClassBoard teams={teams} />

      <section className="border-b border-ink/10 bg-white">
        <div className="container-page py-8">
          <p className="eyebrow">Building it</p>
          <h2 className="mt-2 font-display text-xl font-bold text-ink">
            The pages every team shares
          </h2>
          <p className="mt-2 max-w-2xl text-sm leading-relaxed text-ink/70">
            Teams work from three documents that reference each other: their build
            cards, their architecture, then the code. These are the same for
            everybody, including the one the designers work from.
          </p>
          <div className="mt-4 flex flex-wrap gap-3">
            <a href="/build/instructions.html" className="btn-primary" target="_blank" rel="noopener">
              How to build your app
            </a>
            <a
              href="/build/patterns.html"
              className="rounded-md border border-blaze-maroon px-5 py-2.5 text-center font-medium text-blaze-maroon hover:bg-blaze-maroon/5"
              target="_blank"
              rel="noopener"
            >
              The Anvil Pattern Book
            </a>
            <Link href="/trail-crew/write" className="btn-primary">
              Write a user story
            </Link>
            <a
              href="/build/figma.html"
              className="rounded-md border border-blaze-maroon px-5 py-2.5 text-center font-medium text-blaze-maroon hover:bg-blaze-maroon/5"
              target="_blank"
              rel="noopener"
            >
              Designing for Anvil
            </a>
          </div>
        </div>
      </section>

      <section className="bg-stone-white">
        <div className="container-page py-16 md:py-20">
          {teams.length === 0 ? (
            <p className="text-lg text-ink/70">
              No teams have been published yet. Add a folder under{" "}
              <code className="rounded bg-ink/5 px-1.5 py-0.5 text-sm">docs/students</code> and run{" "}
              <code className="rounded bg-ink/5 px-1.5 py-0.5 text-sm">npm run prototypes</code>.
            </p>
          ) : (
            <>
              <p className="eyebrow">
                {teams.length === 1 ? "1 team" : `${teams.length} teams`}
              </p>
              <div className="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">
                {teams.map((team) => (
                  <article
                    key={team.slug}
                    className="flex flex-col rounded-xl border border-ink/10 bg-white p-6 shadow-sm"
                  >
                    <h2 className="font-display text-xl font-bold text-blaze-maroon">
                      {team.productName}
                    </h2>
                    {team.teamName &&
                      team.teamName.trim().toLowerCase() !==
                        team.productName.trim().toLowerCase() && (
                        <p className="mt-1 text-sm text-hokie-gray">by {team.teamName}</p>
                      )}
                    <p className="mt-3 flex-1 text-sm leading-relaxed text-ink/75">
                      {team.purpose.length > 220
                        ? `${team.purpose.slice(0, 219).trimEnd()}...`
                        : team.purpose}
                    </p>

                    {team.features.length > 0 && (
                      <ul className="mt-4 flex flex-wrap gap-1.5">
                        {team.features.slice(0, 5).map((feature) => (
                          <li
                            key={feature}
                            className="rounded-full bg-blaze-maroon/5 px-2.5 py-1 text-xs text-blaze-maroon"
                          >
                            {feature}
                          </li>
                        ))}
                      </ul>
                    )}

                    <dl className="mt-5 flex gap-5 border-t border-ink/10 pt-4 text-xs text-hokie-gray">
                      <div>
                        <dt className="sr-only">User stories</dt>
                        <dd>
                          <span className="text-base font-semibold text-ink">
                            {team.stats.stories}
                          </span>{" "}
                          {team.stats.stories === 1 ? "story" : "stories"}
                        </dd>
                      </div>
                      <div>
                        <dt className="sr-only">Screens</dt>
                        <dd>
                          <span className="text-base font-semibold text-ink">
                            {team.stats.screens}
                          </span>{" "}
                          {team.stats.screens === 1 ? "screen" : "screens"}
                        </dd>
                      </div>
                    </dl>

                    {team.gapHref && (
                      <a
                        href={team.gapHref}
                        className="mt-5 block rounded-lg border border-trail-orange/40 bg-trail-orange/5 p-4 hover:bg-trail-orange/10"
                        target="_blank"
                        rel="noopener"
                      >
                        <span className="text-xs font-semibold uppercase tracking-wide text-trail-orange">
                          Next: {STAGE_LABEL[team.stage ?? "plan"] ?? team.stage}
                        </span>
                        <span className="mt-1 block text-sm leading-relaxed text-ink/80">
                          {team.next ?? "Nothing this page can see. Go and build."}
                        </span>
                        <span className="mt-2 block text-sm font-medium text-blaze-maroon underline underline-offset-2">
                          What next, and ask about it
                        </span>
                      </a>
                    )}

                    <a
                      href={team.href}
                      className="btn-primary mt-4 text-center"
                      target="_blank"
                      rel="noopener"
                    >
                      Open the prototype
                    </a>
                    {LIVE_SITES[team.slug] && (
                      <a
                        href={LIVE_SITES[team.slug]}
                        className="mt-2 rounded-md bg-trail-orange px-5 py-2.5 text-center font-medium text-white hover:bg-impact-orange"
                      >
                        Open the live site
                      </a>
                    )}

                    {/* The rest are references a team goes to on purpose, so
                        they are links rather than five more buttons that look
                        exactly like the one that matters. */}
                    {(team.buildHref || team.testPlanHref || team.designHref) && (
                      <p className="mt-3 flex flex-wrap gap-x-4 gap-y-1 text-sm text-blaze-maroon">
                        {team.buildHref && (
                          <a href={team.buildHref} className="underline underline-offset-2 hover:text-trail-orange" target="_blank" rel="noopener">
                            Build guide
                          </a>
                        )}
                        {team.testPlanHref && (
                          <a href={team.testPlanHref} className="underline underline-offset-2 hover:text-trail-orange" target="_blank" rel="noopener">
                            Test plan
                          </a>
                        )}
                        {team.designHref && (
                          <a href={team.designHref} className="underline underline-offset-2 hover:text-trail-orange" target="_blank" rel="noopener">
                            Design brief
                          </a>
                        )}
                      </p>
                    )}
                  </article>
                ))}
              </div>
            </>
          )}

          <div className="mt-14 max-w-2xl border-t border-ink/10 pt-8">
            <p className="eyebrow">How these were made</p>
            <h2 className="mt-3 font-display text-2xl font-bold text-ink">
              The prototype is only as good as the writing behind it.
            </h2>
            <p className="mt-4 leading-relaxed text-ink/75">
              There is no model generating these. A feature becomes a screen. A
              user story becomes something on that screen. The line that says
              &ldquo;when the driver taps report a delay&rdquo; becomes a button,
              and the line that says what happens next is what the button tells
              you. A feature nobody wrote a story for arrives as an empty screen
              that says so.
            </p>
            <p className="mt-4 leading-relaxed text-ink/75">
              That is the point. A team that wants a better prototype has exactly
              one thing to change, and it is the part of the work that usually
              feels like it does not matter yet.
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
